app.title=Інтелектуальна система прогнозування успішності студентів
app.version=1.0
window.width=800
window.height=600

data.file=resources/students.csv
report.file=report.txt

model.learningRate=0.01
model.epochs=1000